database:
    #sqlite or mysql
    type: sqlite

    #below options are only for mysql
    host: localhost
    port: 3306
    db-name: gangs
    user: root
    password: ""

gangs:
    ranks: [rookie,rookie1,rookie2,leader]
    ranks-with-invite-perms: [rookie2,leader]
