database:
    #sqlite or mysql
    type: sqlite

    #below options are only for mysql
    host: localhost
    port: 3306
    db-name: gangs
    user: root
    password: ""


gangs:
    ranks: [rookie,rookie1,rookie2,leader]
    ranks-with-invite-perms: [rookie,rookie1,rookie2,leader]
    ranks-with-rank-perms: [rookie,rookie1,rookie2,leader]
    ranks-with-kick-perms: [rookie,rookie1,rookie2,leader]
    ranks-with-disband-perms: [rookie,rookie1,rookie2,leader]
    ranks-with-ally-perms: [rookie,rookie1,rookie2,leader]
    force-friendly-fire: false
    force-friendly-fire-disable : false
    friendly-fire-gang: true
    force-friendly-fire-disable-allies: false
    friendly-fire-allies: true

    ranks-with-friendly-fire-perms: [rookie,rookie1,rookie2,leader]



