name: Gangs
version: '${version}'
main: com.orang3i.gangs.Gangs
api-version: '1.20'
commands:
  tester:
  setgang:
  getgang:
  getgangmembers:
  gangs:
  adventurecommand:
  test-economy:
permissions:
  gangs.tp:
    default: true
  gangs.admin:
    default: op

